#import "/template/template.typ": verbale, team

#show: verbale.with(
  title: "Verbale interno del 10/03/2025",
  sommario: "Verbale che riassume la riunione del 10/03/2025.",
  autore: team.M,
  verificatore: team.G,
  durata_luogo: ("9:30", "11:50", "chiamata Discord"),
  partecipanti: (team.A, team.S, team.T, team.M, team.G, team.C, team.L),
  ordine_giorno: ("Sprint planning",),
  riassunto: [Il gruppo si è riunito per pianificare lo sprint 8. Durante la riunione sono state discusse le attività da svolgere che riguarderanno principalmente la progettazione e la codifica. Le issue sono state rese più atomiche possibile al fine di agevolare il lavoro di ciascun membro. Infine sono state assegnate le issue e sono state stimate le ore necessarie per completarle.
  ],
  decisioni: (
    ([Piano di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/429")[Issue \#429]#footnote(link("https://github.com/techminds-unipd/docs/issues/429")): Consuntivo sprint 7 e aggiornamento preventivo a finire],
      [#link("https://github.com/techminds-unipd/docs/issues/433")[Issue \#433]#footnote(link("https://github.com/techminds-unipd/docs/issues/433")): Preventivo sprint 8],
    ),
    ([Nome di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/434")[Issue \#434]#footnote(link("https://github.com/techminds-unipd/docs/issues/434")): Documentare progettazione in norme di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/435")[Issue \#435]#footnote(link("https://github.com/techminds-unipd/docs/issues/435")): Documentare codifica in norme di progetto],
    ),
    ([Specifica tecnica],
      [#link("https://github.com/techminds-unipd/docs/issues/436")[Issue \#436]#footnote(link("https://github.com/techminds-unipd/docs/issues/436")): Descrizione funzionalità backend login],
      [#link("https://github.com/techminds-unipd/docs/issues/437")[Issue \#437]#footnote(link("https://github.com/techminds-unipd/docs/issues/437")): Descrizione funzionalità backend CreateWorkflow],
      [#link("https://github.com/techminds-unipd/docs/issues/438")[Issue \#438]#footnote(link("https://github.com/techminds-unipd/docs/issues/438")): Descrizione funzionalità backend GetWorkflow],
      [#link("https://github.com/techminds-unipd/docs/issues/439")[Issue \#439]#footnote(link("https://github.com/techminds-unipd/docs/issues/439")): Descrizione funzionalità backend SaveWorkflow],
      [#link("https://github.com/techminds-unipd/docs/issues/440")[Issue \#440]#footnote(link("https://github.com/techminds-unipd/docs/issues/440")): Descrizione funzionalità backend DeleteWorkflow],
      [#link("https://github.com/techminds-unipd/docs/issues/441")[Issue \#441]#footnote(link("https://github.com/techminds-unipd/docs/issues/441")): Descrizione funzionalità backend WorkflowNameList],
      [#link("https://github.com/techminds-unipd/docs/issues/442")[Issue \#442]#footnote(link("https://github.com/techminds-unipd/docs/issues/442")): Descrizione funzionalità backend ExecuteWorkflow],
      [#link("https://github.com/techminds-unipd/docs/issues/443")[Issue \#443]#footnote(link("https://github.com/techminds-unipd/docs/issues/443")): Descrizione funzionalità backend ConnectionGoogleAccount],
      [#link("https://github.com/techminds-unipd/docs/issues/444")[Issue \#444]#footnote(link("https://github.com/techminds-unipd/docs/issues/444")): Descrizione dati di application, business e persistence],
      [#link("https://github.com/techminds-unipd/docs/issues/445")[Issue \#445]#footnote(link("https://github.com/techminds-unipd/docs/issues/445")): Descrizione agente],
      [#link("https://github.com/techminds-unipd/docs/issues/446")[Issue \#446]#footnote(link("https://github.com/techminds-unipd/docs/issues/446")): Descrizione database],
      [#link("https://github.com/techminds-unipd/docs/issues/447")[Issue \#447]#footnote(link("https://github.com/techminds-unipd/docs/issues/447")): Descrizione frontend CustomNodes],
      [#link("https://github.com/techminds-unipd/docs/issues/448")[Issue \#448]#footnote(link("https://github.com/techminds-unipd/docs/issues/448")): Descrizione frontend Navbar],
      [#link("https://github.com/techminds-unipd/docs/issues/449")[Issue \#449]#footnote(link("https://github.com/techminds-unipd/docs/issues/449")): Descrizione frontend Footer],
      [#link("https://github.com/techminds-unipd/docs/issues/450")[Issue \#450]#footnote(link("https://github.com/techminds-unipd/docs/issues/450")): Descrizione frontend Home],
      [#link("https://github.com/techminds-unipd/docs/issues/451")[Issue \#451]#footnote(link("https://github.com/techminds-unipd/docs/issues/451")): Descrizione frontend AboutUs],
      [#link("https://github.com/techminds-unipd/docs/issues/452")[Issue \#452]#footnote(link("https://github.com/techminds-unipd/docs/issues/452")): Descrizione frontend SignIn],
      [#link("https://github.com/techminds-unipd/docs/issues/453")[Issue \#453]#footnote(link("https://github.com/techminds-unipd/docs/issues/453")): Descrizione frontend SignUp],
      [#link("https://github.com/techminds-unipd/docs/issues/454")[Issue \#454]#footnote(link("https://github.com/techminds-unipd/docs/issues/454")): Descrizione frontend Workflow],
      [#link("https://github.com/techminds-unipd/docs/issues/455")[Issue \#455]#footnote(link("https://github.com/techminds-unipd/docs/issues/455")): Descrizione frontend Services],
    ),
    ([MVP],
      [#link("https://github.com/techminds-unipd/mvp/issues/4")[Issue \#4]#footnote(link("https://github.com/techminds-unipd/mvp/issues/4")): Codifica agente],
      [#link("https://github.com/techminds-unipd/mvp/issues/5")[Issue \#5]#footnote(link("https://github.com/techminds-unipd/mvp/issues/5")): Codifica funzionalità backend ConnectionGoogleAccount],
      [#link("https://github.com/techminds-unipd/mvp/issues/6")[Issue \#6]#footnote(link("https://github.com/techminds-unipd/mvp/issues/6")): Codifica funzionalità backend ExecuteWorkflow],
      [#link("https://github.com/techminds-unipd/mvp/issues/7")[Issue \#7]#footnote(link("https://github.com/techminds-unipd/mvp/issues/7")): Codifica funzionalità backend WorkflowNameList],
      [#link("https://github.com/techminds-unipd/mvp/issues/8")[Issue \#8]#footnote(link("https://github.com/techminds-unipd/mvp/issues/8")): Codifica funzionalità backend DeleteWorkflow],
      [#link("https://github.com/techminds-unipd/mvp/issues/9")[Issue \#9]#footnote(link("https://github.com/techminds-unipd/mvp/issues/9")): Codifica funzionalità backend SaveWorkflow],
      [#link("https://github.com/techminds-unipd/mvp/issues/10")[Issue \#10]#footnote(link("https://github.com/techminds-unipd/mvp/issues/10")): Codifica funzionalità backend GetWorkflow],
      [#link("https://github.com/techminds-unipd/mvp/issues/11")[Issue \#11]#footnote(link("https://github.com/techminds-unipd/mvp/issues/11")): Codifica funzionalità backend CreateWorkflow],
      [#link("https://github.com/techminds-unipd/mvp/issues/12")[Issue \#12]#footnote(link("https://github.com/techminds-unipd/mvp/issues/12")): Codifica funzionalità backend login],
      [#link("https://github.com/techminds-unipd/mvp/issues/13")[Issue \#13]#footnote(link("https://github.com/techminds-unipd/mvp/issues/13")): Codifica funzionalità backend RegisterUser],
      [#link("https://github.com/techminds-unipd/mvp/issues/14")[Issue \#14]#footnote(link("https://github.com/techminds-unipd/mvp/issues/14")): Codifica frontend Navbar],
      [#link("https://github.com/techminds-unipd/mvp/issues/15")[Issue \#15]#footnote(link("https://github.com/techminds-unipd/mvp/issues/15")): Codifica frontend CustomNodes],
      [#link("https://github.com/techminds-unipd/mvp/issues/16")[Issue \#16]#footnote(link("https://github.com/techminds-unipd/mvp/issues/16")): Codifica frontend Footer],
      [#link("https://github.com/techminds-unipd/mvp/issues/17")[Issue \#17]#footnote(link("https://github.com/techminds-unipd/mvp/issues/17")): Codifica frontend Home],
      [#link("https://github.com/techminds-unipd/mvp/issues/18")[Issue \#18]#footnote(link("https://github.com/techminds-unipd/mvp/issues/18")): Codifica frontend AboutUs],
      [#link("https://github.com/techminds-unipd/mvp/issues/19")[Issue \#19]#footnote(link("https://github.com/techminds-unipd/mvp/issues/19")): Codifica frontend SignIn],
      [#link("https://github.com/techminds-unipd/mvp/issues/20")[Issue \#20]#footnote(link("https://github.com/techminds-unipd/mvp/issues/20")): Codifica frontend SignUp],
      [#link("https://github.com/techminds-unipd/mvp/issues/21")[Issue \#21]#footnote(link("https://github.com/techminds-unipd/mvp/issues/21")): Codifica frontend Workflow],
      [#link("https://github.com/techminds-unipd/mvp/issues/22")[Issue \#22]#footnote(link("https://github.com/techminds-unipd/mvp/issues/22")): Codifica frontend Services],
    ),
  ),
  firma: false
)