#import "/template/template.typ": verbale, team

#show: verbale.with(
  title: "Verbale interno del 24/03/2025",
  sommario: "Verbale che riassume la riunione del 24/03/2025.",
  autore: team.C,
  verificatore: team.S,
  durata_luogo: ("9:15", "11:15", "chiamata Discord"),
  partecipanti: (team.A, team.S, team.T, team.M, team.G, team.C, team.L),
  ordine_giorno: ("Sprint planning",),
  riassunto: [Il gruppo si è riunito per pianificare lo sprint 9. Durante la riunione il gruppo ha individuato le attività da svolgere al fine di completare l'MVP e terminare la redazione della documentazione con lo scopo di candidarsi per la revisione PB entro i termini previsti. Inoltre il gruppo porterà a termine le issue che non sono state completate nello scorso sprint, ovvero:
  - #link("https://github.com/techminds-unipd/docs/issues/454")[Issue \#454]#footnote(link("https://github.com/techminds-unipd/docs/issues/454")): Descrizione frontend Workflow;
  - #link("https://github.com/techminds-unipd/docs/issues/455")[Issue \#455]#footnote(link("https://github.com/techminds-unipd/docs/issues/455")): Descrizione frontend Services.
  Le issue che non rientravano nello sprint backlog dello sprint 8, sono invece state inserite nello sprint backlog dello sprint 9:
  - #link("https://github.com/techminds-unipd/mvp/issues/21")[Issue \#21]#footnote(link("https://github.com/techminds-unipd/mvp/issues/21")): Codifica frontend Workflow;
  - #link("https://github.com/techminds-unipd/mvp/issues/22")[Issue \#22]#footnote(link("https://github.com/techminds-unipd/mvp/issues/22")): Codifica frontend Services.
  Sono state infine stimate le ore che ciascun membro del gruppo prevede di svolgere.],
  decisioni: (
    ([Piano di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/507")[Issue \#507]#footnote(link("https://github.com/techminds-unipd/docs/issues/507")): Preventivo sprint 9],
    ),
    ([Analisi dei requisiti],
      [#link("https://github.com/techminds-unipd/docs/issues/511")[Issue \#511]#footnote(link("https://github.com/techminds-unipd/docs/issues/511")): Aggiornare UC26],
    ),
    ([Piano di qualifica],
      [#link("https://github.com/techminds-unipd/docs/issues/512")[Issue \#512]#footnote(link("https://github.com/techminds-unipd/docs/issues/512")): Aggiornare cruscotto piano di qualifica],
      [#link("https://github.com/techminds-unipd/docs/issues/486")[Issue \#486]#footnote(link("https://github.com/techminds-unipd/docs/issues/486")): Documentare test di integrazione frontend sul piano di qualifica],
      [#link("https://github.com/techminds-unipd/docs/issues/484")[Issue \#484]#footnote(link("https://github.com/techminds-unipd/docs/issues/484")): Documentare test di unità frontend sul piano di qualifica],
    ),
    ([Nome di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/427")[Issue \#427]#footnote(link("https://github.com/techminds-unipd/docs/issues/427")): Documentare struttura documenti],
      [#link("https://github.com/techminds-unipd/docs/issues/520")[Issue \#520]#footnote(link("https://github.com/techminds-unipd/docs/issues/520")): Testing in norme di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/521")[Issue \#521]#footnote(link("https://github.com/techminds-unipd/docs/issues/521")): Aggiornare progettazione in norme di progetto],
      [#link("https://github.com/techminds-unipd/docs/issues/522")[Issue \#522]#footnote(link("https://github.com/techminds-unipd/docs/issues/522")): Definire standard ISO/IEC 9126 in norme di progetto],
    ),
    ([Manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/428")[Issue \#428]#footnote(link("https://github.com/techminds-unipd/docs/issues/428")): Struttura manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/513")[Issue \#513]#footnote(link("https://github.com/techminds-unipd/docs/issues/513")): Documentare Home in manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/514")[Issue \#514]#footnote(link("https://github.com/techminds-unipd/docs/issues/514")): Documentare About Us in manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/515")[Issue \#515]#footnote(link("https://github.com/techminds-unipd/docs/issues/515")): Documentare SignIn in manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/516")[Issue \#516]#footnote(link("https://github.com/techminds-unipd/docs/issues/516")): Documentare SignUp in manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/517")[Issue \#517]#footnote(link("https://github.com/techminds-unipd/docs/issues/517")): Documentare Dashboard in manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/518")[Issue \#518]#footnote(link("https://github.com/techminds-unipd/docs/issues/518")): Documentare Services in manuale utente],
      [#link("https://github.com/techminds-unipd/docs/issues/519")[Issue \#519]#footnote(link("https://github.com/techminds-unipd/docs/issues/519")): Documentare Workflow in manuale utente],
    ),
    ([Specifica tecnica],
      [#link("https://github.com/techminds-unipd/docs/issues/474")[Issue \#474]#footnote(link("https://github.com/techminds-unipd/docs/issues/474")): Inserire immagini backend, agente e database],
      [#link("https://github.com/techminds-unipd/docs/issues/503")[Issue \#503]#footnote(link("https://github.com/techminds-unipd/docs/issues/503")): Fix specifica],
      [#link("https://github.com/techminds-unipd/docs/issues/506")[Issue \#506]#footnote(link("https://github.com/techminds-unipd/docs/issues/506")): Inserire immagini frontend],
      [#link("https://github.com/techminds-unipd/docs/issues/508")[Issue \#508]#footnote(link("https://github.com/techminds-unipd/docs/issues/508")): Documentare architettura di deploy],
      [#link("https://github.com/techminds-unipd/docs/issues/509")[Issue \#509]#footnote(link("https://github.com/techminds-unipd/docs/issues/509")): Documentare limiti e criticità],
      [#link("https://github.com/techminds-unipd/docs/issues/510")[Issue \#510]#footnote(link("https://github.com/techminds-unipd/docs/issues/510")): Documentare design pattern e diagramma delle classi],
    ),
    ([Lettera di presentazione PB],
      [#link("https://github.com/techminds-unipd/docs/issues/523")[Issue \#523]#footnote(link("https://github.com/techminds-unipd/docs/issues/523")): Lettera di presentazione PB],
    ),
    ([MVP],
      [#link("https://github.com/techminds-unipd/mvp/issues/61")[Issue \#61]#footnote(link("https://github.com/techminds-unipd/mvp/issues/61")): Rendere esplicite le dipendenze e cambiare nome file],
      [#link("https://github.com/techminds-unipd/mvp/issues/62")[Issue \#62]#footnote(link("https://github.com/techminds-unipd/mvp/issues/62")): Test di integrazione frontend],
      [#link("https://github.com/techminds-unipd/mvp/issues/63")[Issue \#63]#footnote(link("https://github.com/techminds-unipd/mvp/issues/63")): Sistemare docker per release],
      [#link("https://github.com/techminds-unipd/mvp/issues/64")[Issue \#64]#footnote(link("https://github.com/techminds-unipd/mvp/issues/64")): Implementare test di sistema],
      [#link("https://github.com/techminds-unipd/mvp/issues/65")[Issue \#65]#footnote(link("https://github.com/techminds-unipd/mvp/issues/65")): Tracciamento test],
    ),
  ),
  firma: false
)