name: PR Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install typst
      run: |
        wget -nv https://github.com/typst/typst/releases/download/v0.12.0/typst-x86_64-unknown-linux-musl.tar.xz
        tar xf typst*.tar.xz -C /tmp
        sudo mv /tmp/typst*/typst /bin/typst
    - name: Check Glossario
      run: python .github/workflows/check_glossario.py
    - name: Indice di Gulpease
      run: python .github/workflows/indice_gulpease.py
    - name: Check ordinamento glossario
      run: python .github/workflows/ordinamento_glossario.py
    - name: Build sources
      run: python .github/workflows/build_sources.py
    - name: Build html
      run: python .github/workflows/build_html.py
